#!/bin/bash

mydir="$(dirname $0)"

use_inotify=""
if [ x"$1" = "x-i" ]; then
    use_inotify=true
    shift
    if [ ! -x "`which inotifywait`" ]; then
	echo "Error: No inotifywait program found (install inotify-tools?)" 1>&2
	exit 2
    fi
fi

if [ x"$1" = "x-h" -o x"$1" = "x-?" ]; then
    echo "Usage: $0 [-i] [buildpager-args]" 1>&2
    echo "With -i, use inotifywait instead of sleeping" 1>&2
    exit 2
fi

m=""
if [ -x "$mydir/buildpager" ]; then
    m="$mydir/buildpager"
elif [ -x "$(type -path buildpager)" ]; then
    m=buildpager
else
    echo "Error: Required program buildpager not found" 1>&2
    exit 2
fi

tmpfile=/tmp/$$
trap "rm -f $tmpfile" 0

watchdir=.

if [ $(basename $PWD) = "build" ] && [ -f ./build.ninja ]; then
    echo "Note: We appear to be in a build directory; watching parent directory" 1>&2
    watchdir=..
    sleep 2
fi

"$m" -x "$@"

while true; do

    echo -e "\r\033[34;47m(building...)\033[00m             "
    if "$m" -x "$@" > "$tmpfile"; then
	clear
	echo
	echo " ** Up-to-date in `pwd`"
    else 
	clear
	tail -35 "$tmpfile"
    fi

    echo

    if [ -n "$use_inotify" ]; then
	echo -ne "\033[31;37m(watching...)\033[00m"
	inotifywait $timeout_flags -e close_write -r "$watchdir" >/dev/null 2>&1
    else 
	echo -ne "\033[34;47m(q<RET> to quit) \033[00m"
	read -t 5 x
	if [ x"$x" = "xq" ]; then
	    exit 0
	fi
    fi

done
